### ISSUE TITLE
[Android] Crash: NoSuchMethodException ViewPagerFragment.<init>

### ISSUE THREAD

**Issue by LenaZhuk** [callstack/react-native-pager-view#283]
## Environment

"react-native": "0.62.2"
"@react-native-community/viewpager": "^5.0.5"

Devices: Samsung Galaxy A31 (Android 10), Samsung Galaxy A11 (Android 10), Samsung Galaxy J5 (Android 9)

## Description

Crash in Firebase Crashlytics report:

Caused by java.lang.NoSuchMethodException
com.reactnativecommunity.viewpager.ViewPagerFragment.<init> []

## Stack trace

Caused by java.lang.NoSuchMethodException: com.reactnativecommunity.viewpager.ViewPagerFragment.<init> []
       at java.lang.Class.getConstructor0(Class.java:2332)
       at java.lang.Class.getConstructor(Class.java:1728)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
       at com.ellorem.oxygean.MainActivity.onCreate(MainActivity.java:15)
       at android.app.Activity.performCreate(Activity.java:7963)
       at android.app.Activity.performCreate(Activity.java:7952)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by troZee** [comment]
Hey @LenaZhuk 
Thank you for reporting an issue. Do you know, how to reproduce it ?

**Comment by arekkubaczkowski** [comment]
@LenaZhuk I've investigated a bit into this issue and I've found potential solution but unfortunately because this error not occurs on local environment I am not able to reproduce it and I want to ask you for do it once we release the next version and let us know whether it helped. Thanks!

**Comment by LenaZhuk** [comment]
@arekkubaczkowski Thank you!
