### ISSUE TITLE
Crash when use react-native-navigation

### ISSUE THREAD

**Issue by supermaverickws** [callstack/react-native-pager-view#344]
When use react-native-navigation push stack. some times App will crash and log it:

```java
 E/unknown:NativeViewHierarchyManager: Unable to update properties for view tag 173
    com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 173 could not be found.
    
        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:112)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:139)
        at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:291)
        at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:417)
        at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:114)
        at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:655)
        at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:521)
        at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:483)
        at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
        at com.reactnativepagerview.PagerViewViewManager$createViewInstance$1.onPageScrolled(PagerViewViewManager.kt:38)
        at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrolled(CompositeOnPageChangeCallback.java:59)
        at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrolled(CompositeOnPageChangeCallback.java:59)
        at androidx.viewpager2.widget.ScrollEventAdapter.dispatchScrolled(ScrollEventAdapter.java:438)
        at androidx.viewpager2.widget.ScrollEventAdapter.onScrolled(ScrollEventAdapter.java:201)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4231)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3862)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:23109)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
        at android.view.View.layout(View.java:23109)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:255)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:223)
        at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:163)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1079)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1075)
        at android.view.Choreographer.doCallbacks(Choreographer.java:897)
        at android.view.Choreographer.doFrame(Choreographer.java:822)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1062)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
```

**Comment by efstathiosntonas** [comment]
what react-native version you're using?

**Comment by supermaverickws** [comment]
0.64 @efstathiosntonas

**Comment by troZee** [comment]
Hello @supermaverickws 
Could you provide a reproducible repository ? Or you can clone this repo and add an another example with rnn

**Comment by efstathiosntonas** [comment]
i think the issue is raising because of https://github.com/facebook/react-native/issues/31245

**Comment by supermaverickws** [comment]
@troZee @efstathiosntonas . many thanks for so fast and nice replay this issue. i will try resolve it downgrading to 0.63.

**Comment by danilobuerger** [comment]
Why close this though? Downgrading shouldn't be a solution.

**Comment by danilobuerger** [comment]
This only happens with rn64 & pager-view v5, downgrading to pager-view v4 also resolves the crash.

**Comment by srfaytkn** [comment]
@troZee Is there any progress in this issue?

**Comment by EM-Sabeel** [comment]
@troZee Is there any progress on this issue? I'm also getting this issue in beta version `v6.0.0-rc.0`
