### ISSUE TITLE
Android crash 

### ISSUE THREAD

**Issue by AymerZhang** [callstack/react-native-pager-view#345]
## Environment

HUAWEI MATE 20 pro. 
Android 10.0

## Description

Occasionally crash 

## Reproducible Demo

crashLog:
API level: '29'
OS version: '10'
ABI list: 'arm64-v8a,armeabi-v7a,armeabi'
Manufacturer: 'HUAWEI'
Brand: 'HUAWEI'
Model: 'LYA-AL00'
Build fingerprint: 'HUAWEI/LYA-AL00/HWLYA:10/HUAWEILYA-AL00/10.1.0.163C00:user/release-keys'
pid: 1584, tid: 1584, name: main  >>> com.chehejia.oc.m01 <<<

java stacktrace:
kotlin.KotlinNullPointerException
	at com.reactnativepagerview.PagerViewViewManager.createViewInstance(PagerViewViewManager.kt:30)
	at com.reactnativepagerview.PagerViewViewManager.createViewInstance(PagerViewViewManager.kt:21)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:261)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:911)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:986)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8387)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by troZee** [comment]
duplicated https://github.com/callstack/react-native-pager-view/issues/323
