### ISSUE TITLE
[Android] Crash on PagerViewViewManager.java line 30

### ISSUE THREAD

**Issue by thanakij** [callstack/react-native-pager-view#352]
## Environment

```
PagerViewViewManager.java line 30
com.reactnativepagerview.PagerViewViewManager.createViewInstance
```

```
react-native-pager-view 5.1.7
react-native 0.62.2
platform: Android
```

## Description

I am using **react-native-pager-view 5.1.7** for our onboarding after new app installations.
And it works great. However, there are a crash happening for some portion of our Android users.
Although I cannot reproduce this, this crash is among our top two in Crashlytics report so far.

Below is from the [code](https://github.com/callstack/react-native-pager-view/blob/master/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt#L30):

```
val adapter = FragmentAdapter((reactContext.currentActivity as FragmentActivity?)!!)
```

What is suspicious here is the use of "?" and "!!" at the same time. My understanding is that "?" is needed here. Otherwise, it won't compile. But the use of "!!" just skips the null handling part.

Next, I tried to do some quick search and find that it can be [common that getCurrentActivity is null](https://github.com/facebook/react-native/issues/18345).

The solution then is to properly handle the null case.

## Reproducible Demo

I cannot reproduce this myself but I have a guess. Because I am using this lib for my onboarding process. Could it be that after newly installation the user simply pressed the button on the device to shutdown phone's screen. And, with the right timing, the activity is forced to be null because the device in put in some sleep/inactive mode.

**Comment by listenzz** [comment]
Maybe same problem.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.h androidx.fragment.app.c.getSupportFragmentManager()' on a null object reference
    at androidx.viewpager2.adapter.FragmentStateAdapter.<init>(SourceFile:1)
    at com.reactnativecommunity.viewpager.b.<init>(SourceFile:1)
    at com.reactnativecommunity.viewpager.ReactViewPagerManager.createViewInstance(SourceFile:3)
    at com.reactnativecommunity.viewpager.ReactViewPagerManager.createViewInstance(SourceFile:1)
    at com.facebook.react.uimanager.ViewManager.createViewInstance(SourceFile:1)
    at com.facebook.react.uimanager.ViewManager.createView(SourceFile:2)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(SourceFile:7)
    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(SourceFile:2)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(SourceFile:15)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(SourceFile:10)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(SourceFile:1)
    at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(SourceFile:1)
    at com.facebook.react.bridge.GuardedRunnable.run(SourceFile:1)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8349)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by thanakij** [comment]
It is from the same `createViewInstance` so I agree that it can be the same issue as mine.

**Comment by thanakij** [comment]
Alright, I've found that there was an old issue #174 that was closed without solution. But now, we have a lot more detail (crash log + line number) so hopefully this would be of much help for maintainers this time.

**Comment by thanakij** [comment]
Below is my crashlog.

```
Fatal Exception: kotlin.KotlinNullPointerException
       at com.reactnativepagerview.PagerViewViewManager.createViewInstance(PagerViewViewManager.java:30)
       at com.reactnativepagerview.PagerViewViewManager.access$setEventDispatcher$p(PagerViewViewManager.java:21)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:786)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:861)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7830)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
```

**Comment by thanakij** [comment]
Ok, I will close this as it is a dup for #323.
