### ISSUE TITLE
NestedScrollableHost doesn't have ID associated

### ISSUE THREAD

**Issue by luislukas** [callstack/react-native-pager-view#585]
## Environment

react-native-pager-view: 5.4.24

## Description

Because `NestedScrollableHost` is created like:
`val host = NestedScrollableHost(reactContext)` and no specific ID is assigned we are experiencing the following crash:

```
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class androidx.recyclerview.widget.RecyclerView$y instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x1. Make sure other views do not use the same id.06-21 10:52:45.064  600  600 E AndroidRuntime:  at android.view.View.onRestoreInstanceState(View.java:22322)06-21 10:52:45.064  600  600 E AndroidRuntime:  at android.view.View.dispatchRestoreInstanceState(View.java:22294)06-21 10:52:45.064  600  600 E AndroidRuntime:  at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4799)06-21 10:52:45.064  600  600 E AndroidRuntime:  at android.view.View.restoreHierarchyState(View.java:22272)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.Fragment.restoreViewState(Unknown Source:7)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.Fragment.restoreViewState(Unknown Source:26)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.Fragment.performActivityCreated(Unknown Source:18)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.t.a(Unknown Source:26)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.t.m(Unknown Source:100)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.m.e0(Unknown Source:245)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.m.f1(Unknown Source:94)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.m.b0(Unknown Source:21)06-21 10:52:45.064  600  600 E AndroidRuntime:  at androidx.fragment.app.m$g.run(Unknown Source:3)06-21 10:52:45.064  600  600 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:938)06-21 10:52:45.064  600  600 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:99)06-21 10:52:45.064  600  600 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:247)06-21 10:52:45.064  600  600 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:8656)06-21 10:52:45.064  600  600 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)06-21 10:52:45.064  600  600 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)06-21 10:52:45.064  600  600 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

## Reproducible Demo

I can't provide a sample, also, because might be very specific for our project. The crash reproduces for us when the view is recreated. 
A PR to fix this will follow shortly.

**Comment by luislukas** [comment]
I have a PR for this but I'm getting: 
ERROR: Permission to callstack/react-native-pager-view.git denied to xxx.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I've tried raising it with SSH key and usual http. Not sure If I need to be added as contributor?

Thanks.

**Comment by troZee** [comment]
> I have a PR for this but I'm getting: ERROR: Permission to callstack/react-native-pager-view.git denied to xxx. fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.
> 
> I've tried raising it with SSH key and usual http. Not sure If I need to be added as contributor?
> 
> Thanks.

Please follow instructions in this article:
https://opensource.com/article/19/7/create-pull-request-github

**Comment by luislukas** [comment]
Thanks for the link @troZee - I've raised the changes now.
