### ISSUE TITLE
app crashing in react native version 0.75.4  with new architecture

### ISSUE THREAD

**Issue by sankar-gp** [callstack/react-native-pager-view#882]
React Native App crashing 

FATAL EXCEPTION: main
             Process: com.test.app, PID: 11360
             java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{1b4b462 VFED..... ......ID 0,0-975,1964 #2}, adapter:com.reactnativepagerview.ViewPagerAdapter@eb2d9f3, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@58106b0, context:com.facebook.react.uimanager.ThemedReactContext@f0c1813
             	at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6433)
             	at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1456)
             	at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:12699)
             	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13199)
             	at androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:277)
             	at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:213)
             	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
             	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:708)
             	at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(D8$$SyntheticClass:0)
             	at android.animation.Animator.callOnList(Animator.java:666)
             	at android.animation.Animator.notifyListeners(Animator.java:609)
             	at android.animation.Animator.notifyEndListeners(Animator.java:634)
             	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)
             	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1566)
             	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:344)
             	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
             	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:87)
             	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
             	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
             	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
             	at android.view.Choreographer.doFrame(Choreographer.java:941)
             	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
             	at android.os.Handler.handleCallback(Handler.java:959)
             	at android.os.Handler.dispatchMessage(Handler.java:100)
             	at android.os.Looper.loopOnce(Looper.java:232)
             	at android.os.Looper.loop(Looper.java:317)
             	at android.app.ActivityThread.main(ActivityThread.java:8705)
             	at java.lang.reflect.Method.invoke(Native Method)
             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

"react-native": "0.75.4",
"react-native-pager-view": "^6.4.1",

**Comment by emifairais** [comment]
Same issue here.

**Comment by RaduPaun** [comment]
Same here. Please help!  🙏 
"react-native": "0.75.3",
"react-native-pager-view": "6.4.0",

**Comment by raphaelobinna** [comment]
I had the same issue with Execution failed for task ':react-native-pager-view:compileDebugKotlin'.
I downgraded to pager view 6.3.0, it didn't fix it. When I finally downgraded my react-native version from 0.75.4 to 0.75.2 . 

That fixed it for me

**Comment by shovel-kun** [comment]
Where are you folks getting this error? 

Try https://github.com/software-mansion/react-native-screens/commit/b67af8628725a9c112adcf79b0387e523bd191a6. 

It fixed navigating with `navigation.navigate()` for me on new arch and `0.75.4`, but this error occurs when I try to `navigation.replace()`

**Comment by LinhLM23496** [comment]
+ 1

**Comment by MrRefactor** [comment]
Just upgraded `react-native` to `0.75.4` in the example app, everything is working fine. Closing issue https://github.com/callstack/react-native-pager-view/pull/901

**Comment by richardbutler** [comment]
Getting this issue with react-native@0.76.1. I have a PagerView in a Stack.Screen, which may be causing the issue. This doesn't happen using the old arch.

```
    "@react-navigation/native": "7.0.0-rc.21",
    "@react-navigation/native-stack": "7.0.0-rc.30",
    "expo": "~52.0.0-preview.19",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.1",
    "react-native-pager-view": "^6.4.1",
    "react-native-screens": "4.0.0-beta.17",
```

```
ERROR  Your app just crashed. See the error below.
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{9e6e20d VFED..... ......ID 0,0-1124,1426 #2}, adapter:com.reactnativepagerview.ViewPagerAdapter@33c65c2, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@dc49fd3, context:com.facebook.react.uimanager.ThemedReactContext@c5c0835
  androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6433)
  androidx.recyclerview.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:6554)
  androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:9249)
  androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4207)
  androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3862)
  androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
  android.view.View.layout(View.java:24421)
  android.view.ViewGroup.layout(ViewGroup.java:6440)
  androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
  android.view.View.layout(View.java:24421)
  android.view.ViewGroup.layout(ViewGroup.java:6440)
  com.reactnativepagerview.PagerViewViewManagerImpl.refreshViewChildrenLayout$lambda$2(PagerViewViewManagerImpl.kt:157)
  com.reactnativepagerview.PagerViewViewManagerImpl.$r8$lambda$GQgd023cnWEAb4sL7PYFpO-lrvQ(Unknown Source:0)
  com.reactnativepagerview.PagerViewViewManagerImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
  android.os.Handler.handleCallback(Handler.java:958)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:205)
  android.os.Looper.loop(Looper.java:294)
  android.app.ActivityThread.main(ActivityThread.java:8177)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by richardbutler** [comment]
Just tried this with v6.5.0 and the issue persists.

**Comment by renyufei8023** [comment]
There are issues with using react-screens native stack

**Comment by Melekhin** [comment]
+1, crash in change from PageViewer (that in Stack.Screen) in Nested Stack.Screen

    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/material-top-tabs": "^6.6.14",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.11.0",
    "react": "18.3.1",
    "react-native": "^0.76.1",

**Comment by MrRefactor** [comment]
Please provide a reproduction repo.

**Comment by abraaoz** [comment]
(NOBRIDGE) ERROR  Error: Exception in HostFunction: java.lang.IllegalStateException: ViewPager2 does not support direct child views

"react-native": "0.76.2",
"react-native-screens": "4.2.0",
"@react-navigation/native": "7.0.3",

newArch enabled

**Comment by MrRefactor** [comment]
this is an error from core/react-native-screens, for now please use patch as in this PR:
https://github.com/software-mansion/react-native-screens/pull/2527, until https://github.com/facebook/react-native/pull/47634 will be merged into core

**Comment by sankar-gp** [comment]
Issue fixed in callstack/react-native-pager-view v6.5.1, Now i'm not observing the crash

**Comment by Umar-Farooq-Shafi** [comment]
> (NOBRIDGE) ERROR Error: Exception in HostFunction: java.lang.IllegalStateException: ViewPager2 does not support direct child views
> 
> "react-native": "0.76.2", "react-native-screens": "4.2.0", "@react-navigation/native": "7.0.3",
> 
> newArch enabled
> 
> looks like it's related to [software-mansion/react-native-screens#2529](https://github.com/software-mansion/react-native-screens/issues/2529)

I'm getting the same error. How did you solve it?

**Comment by abraaoz** [comment]
@Umar-Farooq-Shafi , you have two options:
1. Apply this patch using https://www.npmjs.com/package/patch-package

[react-native-screens+4.2.0.patch](https://github.com/user-attachments/files/19487006/react-native-screens%2B4.2.0.patch)

OR

2. Upgrade react-native-screens to 4.3.0 or newer.

**Comment by azr-arch** [comment]
I am facing this isssue 

```
"react-native": "0.82.0",
"react-native-screens": "^4.16.0",
"react-native-pager-view": "^6.9.1",
```
