### ISSUE TITLE
[newArch] Crash when going back from a view that has PagerView

### ISSUE THREAD

**Issue by TomCorvus** [callstack/react-native-pager-view#942]
## Environment

Only on Android.

```
    "react-native": "0.76.3",
    "react-native-pager-view": "^6.6.0",
```

## Description

Hello,

When I go back from a view that has PagerView, the application crashes.
It appears with react-native new architecture, I don't reproduce this problem when new arch is not activated.

This problem has appeared since the 6.6.0 version.

## Reproducible Demo

https://github.com/TomCorvus/RNavigation

```
Fatal Exception: java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.f$m{306a6fa VFED..... ......ID 0,0-1080,1766 #6}, adapter:com.reactnativepagerview.i@4e728ec, layout:androidx.viewpager2.widget.f$h@2adbdbc, context:com.facebook.react.uimanager.C0@e204f60
       at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:7071)
       at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1597)
       at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:13655)
       at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:14157)
       at androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:286)
       at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:216)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1112)
```

Thank you.

**Comment by MrRefactor** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v6.6.1

**Comment by marcoamt** [comment]
Hi, I've noticed that the error is still in v6.6.1.

**Comment by troZee** [comment]
@marcoamt could you provide repro steps ?
